# Meta Data for SEO

## Homepage
title = "CCB Doks"
titleSeparator = "-"
titleAddition = "MRC WIMM CCB Documentation"
description = "The MRC WIMM Center for Computational Biology provides High-Performance Computing services to biomedical researchers at the University of Oxford."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["mrc-wimm-ccb.png"]
ogLocale = "en_US"
domainTLD = "kevinrue.github.io/wimm_ccb_docs"
titleHome = "CCB Doks"

## Twitter Cards
twitterSite = "@MRC_WIMM"
twitterCreator = "@KevinRUE67"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "MRC WIMM CCB"
schemaAuthor = "Kevin Rue-Albrecht"
schemaAuthorTwitter = "https://twitter.com/KevinRUE67"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/kevin-rue-albrecht/"
schemaAuthorGitHub = "https://github.com/kevinrue"
schemaLocale = "en-US"
schemaLogo = "mrc-wimm-logo.jpeg"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "mrc-wimm-ccb.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/mrc_wimm"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/kevinrue/wimm_ccb_docs"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/h-enk/doks"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
